name: schedule tasks
run-name: run schedule tasks

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '54 3 * * *'
    - cron: '0 10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
      
      - name: Push success
        if: ${{ github.event_name == 'push' }}
        run: |
          echo git push origin main success.

      - name: Run schedule
        if: ${{ github.event_name == 'schedule' && github.event.schedule != '0 10 * * *' }}
        run: |
          cd run
          sh main.sh
      
      - name: Update schedule
        if: ${{ github.event_name == 'schedule' && github.event.schedule == '0 10 * * *' }}
        run: |
          hour=$(($RANDOM%5))
          min=$(($RANDOM%59))
          sed -i "0,/cron/{s/- cron: '.*\* \* \*'/- cron: '${min} ${hour} * * *'/}" .github/workflows/schedule-actions.yml
          git config --global user.email ${{ secrets.GCON_USER_EMAIL }}
          git config --global user.name ${{ secrets.GCON_USER_NAME }}
          git add .
          git commit -m "update schedule to: ${min} ${hour} * * *"
          git pull --rebase
          git push
